version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=555555
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  # APP*****************************************
  web-server:
    image: web-server:latest
    network_mode: bridge
    container_name: web-server
    expose:
      - 80
    ports:
      - 80:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
